function data()
return {
	en = {

		["mod_name"] = "Lf and El signals",
		["mod_desc"] = "Lf signals are reflective panels that are set up at temporary slow-moving zones. El signals instruct the engine driver of electrically powered vehicles on how to behave at this signal.",

        -- El Signale
        ["El-Signale"] = "El signals",
        ["El_zusatzsignaltafeln_desc"] = "Assets of El additional signs for signals",
        ["El-Signal"] = "El signal",
        ["Version"] = "Version",
        ["alt"] = "old",
        ["neu"] = "new",
        ["Höhe"] = "Height",
        ["hoch"] = "high",
        ["standard"] = "standard",
        ["gleishöhe"] = "track",
        ["boden"] = "terrain",
        ["nein"] = "no",
        ["ja"] = "yes",
        ["X"] = "-X-",
        ["links"] = "left",
        ["rechts"] = "right",
        ["doppelt"] = "double",
        ["gerade"] = "straight",
        ["Verschub für Signal Distance Mod"] = "Shifting for Signal Distance Mod",
        ["Höhenanpassung"] = "Height adjustment",
        ["Snapping für Signale"] = "Snapping for signals",
        ["H/V 48|51"] = "Hv 48/51",
        ["H/V 59"] = "Hv 59",
        ["H/V 69"] = "Hv 69",
        ["H/V Kompakt"] = "Kompakt",
        ["ca. Höhe für Signalsnapping"] = "approx. height for signal snapping",
        ["4 m"] = "4 m",
        ["5 m"] = "5 m",
        ["5,5 m"] = "5.5 m",
        ["6,5 m"] = "6.5 m",
        ["8 m"] = "8 m",

        ["tooltip_el_signal"] = "Selection of El signals as static asset. Entry marked as \"dynamisch\" has a built-in animation to trigger the signal time based (not train based)",
        ["tooltip_version"] = "Selection of version",
        ["tooltip_height"] = "Selection of the height reference point",
        ["tooltip_pole"] = "With pole or without?",
        ["tooltip_arrow"] = "Without arrow or with and if so which direction",
        ["tooltip_distance"] = "If the Signal Distance Mod is installed, the offset can be activated here",
        ["tooltip_heightadjust"] = "Height adjustment of the  signal",
        ["tooltip_snapping"] = "Selection of snapping for signals",
        ["tooltip_snapping_height"] = "Selection of snapping height for signals",

        --Lf1 Signale
        ["Lf1 & Baustellenzubehör"] = "Lf1 to Lf3 signals & construction parts",
        ["Lf1_zusatzsignaltafeln_desc"] = "Assets of Lf1 to Lf3 signals",
        ["Lf-Signal"] = "Lf signal",
        ["Standort"] = "Position",
        ["Geschwindigkeit in km/h"] = "Speed in km/h",
        ["niedrig"] = "low",
        ["Beleuchtung"] = "Lighting",
        ["Lampe DRG 1"] = "Lamp DRG 1",
        ["Lampe DRG 2"] = "Lamp DRG 2",
        ["moderne Lampe"] = "Lamp modern",

        ["tooltip_lf1_signal"] = "Selection of Lf signal",
        ["tooltip_position"] = "Selection of the position at the track",
        ["tooltip_speed"] = "Selection of indicator for speed",
        ["tooltip_lighting"] = "Selection of lamp",

        --Lf Signale
        ["Lf-Signale"] = "Lf6 and Lf7 signals",
        ["Lf_zusatzsignaltafeln_desc"] = "Assets of Lf6 and Lf7 signals",
        ["gedrehtes Lf 6"] = "turned Lf 6",
        ["Zuordnungspfeil rechts"] = "Assignment arrow right",
        ["Zuordnungspfeil links"] = "Assignment arrow left",
        ["beleuchtetes Lf6"] = "Illuminated Lf6",

        ["tooltip_lf_signal"] = "Lf6 and Lf7 signals",
        ["tooltip_turned"] = "Inverted triangle due to lack of space",
        ["tooltip_pfR"] = "Put an assignment arrow on the right?",
        ["tooltip_pfL"] = "Put an assignment arrow on the left?",
        ["tooltip_lighted"] = "Is the Lf6 supposed to light up?",

	},
	de = {

		["mod_name"] = "Lf- und El-Signale",
		["mod_desc"] = "Lf-Signale sind rückstrahlende Tafeln, die bei vorübergehenden Langsamfahrstellen aufstellt werden. El-Signale weisen den Lokführer elektrisch betriebener Fahrzeuge an, wie er sich an diesem Signal verhalten muss.",

        -- El Signale
        ["El-Signale"] = "El-Signale",
        ["El_zusatzsignaltafeln_desc"] = "Assets der El-Zusatztafeln für Signale",
        ["El-Signal"] = "El-Signal",
        ["Version"] = "Version",
        ["alt"] = "alt",
        ["neu"] = "neu",
        ["Höhe"] = "Höhe",
        ["hoch"] = "hoch",
        ["standard"] = "Standard",
        ["gleishöhe"] = "Gleishöhe",
        ["boden"] = "Boden",
        ["nein"] = "nein",
        ["ja"] = "ja",
        ["X"] = "-X-",
        ["links"] = "links",
        ["rechts"] = "rechts",
        ["doppelt"] = "doppelt",
        ["gerade"] = "gerade",
        ["Verschub für Signal Distance Mod"] = "Verschub für Signal Distance Mod",
        ["Höhenanpassung"] = "Höhenanpassung",
        ["Snapping für Signale"] = "Snapping für Signale",
        ["H/V 48|51"] = "Hv 48/51",
        ["H/V 59"] = "Hv 59",
        ["H/V 69"] = "Hv 69",
        ["H/V Kompakt"] = "Kompakt",
        ["ca. Höhe für Signalsnapping"] = "ca. Höhe für Signalsnapping",
        ["4 m"] = "4 m",
        ["5 m"] = "5 m",
        ["5,5 m"] = "5,5 m",
        ["6,5 m"] = "6,5 m",
        ["8 m"] = "8 m",

        ["tooltip_el_signal"] = "Auswahl El-Signals als statische Assets. Eintrag mit \"dynamisch\" schaltet das Signal um als zeitgesteuerte Animation (nicht zugbeeinflusst)",
        ["tooltip_version"] = "Versionsauswahl",
        ["tooltip_height"] = "Auswahl des Referenzpunktes der Höhe",
        ["tooltip_pole"] = "Mit Mast oder ohne?",
        ["tooltip_arrow"] = "Mit Pfeil oder ohne oder in welche Richtung",
        ["tooltip_distance"] = "Wenn der Signal Distanz Mod installiert, kann hier der Versatz aktiviert werden",
        ["tooltip_heightadjust"] = "Höhenanpassung des Signals",
        ["tooltip_snapping"] = "Auswahl der Snapping für Signale",
        ["tooltip_snapping_height"] = "Auswahl der Snappinghöhe für Signale",

        --Lf1 Signale
        ["Lf1 & Baustellenzubehör"] = "Lf1 - Lf3-Signale & Baustellenzubehör",
        ["Lf1_zusatzsignaltafeln_desc"] = "Assets der Lf1- bis Lf3-Signale",
        ["Lf-Signal"] = "Lf-Signal",
        ["Standort"] = "Standort",
        ["Geschwindigkeit in km/h"] = "Geschwindigkeit in km/h",
        ["niedrig"] = "niedrig",
        ["Beleuchtung"] = "Beleuchtung",
        ["Lampe DRG 1"] = "Lampe DRG 1",
        ["Lampe DRG 2"] = "Lampe DRG 2",
        ["moderne Lampe"] = "Lampe modern",

        ["tooltip_lf1_signal"] = "Auswahl Lf-Signal",
        ["tooltip_position"] = "Auswahl der Position am Gleis",
        ["tooltip_speed"] = "Auswahl der Kennziffer für die Geschwindigkeit",
        ["tooltip_lighting"] = "Auswahl der Lampe",

        --Lf Signale
        ["Lf-Signale"] = "Lf6- und Lf7-Signale",
        ["Lf_zusatzsignaltafeln_desc"] = "Assets der Lf6- und Lf7-Signale",
        ["gedrehtes Lf 6"] = "gedrehtes Lf 6",
        ["Zuordnungspfeil rechts"] = "Zuordnungspfeil rechts",
        ["Zuordnungspfeil links"] = "Zuordnungspfeil links",
        ["beleuchtetes Lf6"] = "beleuchtetes Lf6",

        ["tooltip_lf_signal"] = "Lf6- und Lf7-Signale",
        ["tooltip_turned"] = "Umgedrehtes Dreieck wegen Platzmangels",
        ["tooltip_pfR"] = "Einen Zuordnungspfeil rechts anbringen?",
        ["tooltip_pfL"] = "Einen Zuordnungspfeil links anbringen?",
        ["tooltip_lighted"] = "Soll das Lf6 leuchten?",

	},
}
end
